import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Image from "next/image";
import { Button } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export function Footer() {
  return (
    <footer className="bg-[#0b5137] text-white pt-14 pb-6">
      <div className="max-w-7xl mx-auto px-6">

        {/* TOP GRID */}
        <div className="grid md:grid-cols-3 gap-10">

          {/* LEFT — BRAND */}
          <div className="space-y-5">
            <h2 className="text-3xl font-bold">
              Global <span className="text-[#7FAF0D]">Source Expo</span>
            </h2>

            <Button
              variant="contained"
              sx={{
                backgroundColor: "#7FAF0D",
                borderRadius: "10px",
                textTransform: "none",
                px: 3,
              }}
            >
              Connect with us
            </Button>

            <Button
              variant="outlined"
              sx={{
                borderColor: "white",
                color: "white",
                borderRadius: "10px",
                textTransform: "none",
                px: 3,
              }}
            >
              Visit Our Store
            </Button>

            {/* Contact */}
            <div className="pt-3 space-y-3 text-sm">
              <h4 className="font-semibold text-lg">Contact Us</h4>

              <p>Whats App<br />+1 202-918-2132</p>

              <p>Call Us<br />+1 202-918-2132</p>
            </div>

            {/* Download */}
            <div className="pt-3">
              <h4 className="font-semibold mb-2">Download App</h4>

              <div className="flex gap-3">
                <Image
                  src="/appstore.png"
                  alt="appstore"
                  width={140}
                  height={40}
                />
                <Image
                  src="/googleplay.png"
                  alt="googleplay"
                  width={140}
                  height={40}
                />
              </div>
            </div>
          </div>

          {/* MIDDLE — CATEGORIES */}
          <div>
            <h3 className="text-xl font-semibold mb-4 border-b border-white/30 pb-2">
              Most Popular Categories
            </h3>

            <ul className="space-y-2 text-sm">
              <li>(SPICES & HERBS)</li>
              <li>(CLOTHING Section)</li>
              <li>(SEAFOOD)</li>
              <li>JUTE SECTION</li>
              <li>NATURAL AND AYURBEDIC MEDICINE</li>
              <li>Vegetables & Fruits</li>
              <li>HANDICRAFTS SECTION</li>
              <li>Food & Beverage</li>
              <li>Tea & Coffee</li>
              <li>SEEDS WITH AGRI DRONE & ROBOTS</li>
              <li>Kids Toys...</li>
              <li>ECO COOKWARE & UTENSILS</li>
            </ul>

            <Button
              variant="contained"
              sx={{
                mt: 3,
                backgroundColor: "#7FAF0D",
                borderRadius: "10px",
                textTransform: "none",
              }}
            >
              View More
            </Button>
          </div>

          {/* RIGHT — SERVICES */}
          <div>
            <h3 className="text-xl font-semibold mb-4 border-b border-white/30 pb-2">
              Customer Services
            </h3>

            <ul className="space-y-3 text-sm">
              <li>About Us</li>
              <li>Terms & Conditions</li>
              <li>FAQ</li>
              <li>Privacy Policy</li>
              <li>E-waste Policy</li>
              <li>Cancellation & Return Policy</li>
            </ul>
          </div>

        </div>

        {/* BOTTOM */}
        <div className="border-t border-white/20 mt-12 pt-6 text-center text-sm">
          © 2026 All rights reserved. Global Source Expo
        </div>

      </div>
    </footer>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
